language: c

sudo: false

addons:
  apt:
    packages:
    - autoconf

compiler:
  - clang
  - gcc

script:
    - export OMP_NUM_THREADS=1
    - export CFLAGS="-Wno-deprecated-declarations -Wdeclaration-after-statement -Wno-error=unused-variable"
    - ./configure --disable-openmp --with-quantum-depth=16 --enable-hdri=no --with-perl
    - make
    - cd PerlMagick
    - perl Makefile.PL
    - make
